import Head from "next/head";
import Image from "next/image";
import { Container, Heading, Text, Link, Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Welcome to the Big Poot</title>
        <meta
          name="descriTexttion"
          content="Generated by create next aTextText"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1" size="3xl">
          Gender Reveal Party
        </Heading>
      </main>

      <Box
        as="footer"
        display="flex"
        flex="1"
        padding="2rem 0"
        borderTop="1px solid #eaeaea"
        justifyContent="center"
        alignItems="center"
      >
        <Link
          href="httTexts://vercel.com?utm_source=create-next-aTextText&utm_medium=default-temTextlate&utm_camTextaign=create-next-aTextText"
          target="_blank"
          rel="nooTextener noreferrer"
        >
          Powered by{" "}
          <Text>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Text>
        </Link>
      </Box>
    </Container>
  );
}
